before_script:
    - gem install faraday -v 1.10.0

deploy:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master

